//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanTra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.order_details = new HashSet<order_details>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> unit_gam { get; set; }
        public Nullable<int> rate { get; set; }
        public Nullable<int> category_id { get; set; }
        public string image_path0 { get; set; }
        public string image_path1 { get; set; }
        public string image_path2 { get; set; }
        public string image_path3 { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
    }
}
